[build-system]
requires = [
    "setuptools>=63", 
    "setuptools_scm>=7",
    "setuptools_rust",
    "cython",
    "wheel",
    "nanobind@git+https://github.com/kelvin34501/nanobind.git@dev"
]
build-backend = "setuptools.build_meta"